services:
  # Backend API Service
  - type: web
    name: movie-recommendation-backend
    env: node
    plan: free
    region: oregon
    buildCommand: cd backend && npm ci && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: movie-recommendation-db
          property: connectionString
      - key: DB_NAME
        value: moveere_prod
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: BCRYPT_ROUNDS
        value: 12
      - key: LOG_LEVEL
        value: info
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 50
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.vercel.app
    healthCheckPath: /api/health

databases:
  - name: movie-recommendation-db
    databaseName: moveere_prod
    user: moveere_user
    plan: free
    region: oregon