services:
  # Backend API Service
  - type: web
    name: movie-recommendation-backend
    env: node
    plan: free
    region: oregon
    buildCommand: cd backend && npm ci
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://harystyles:Ebuka1234@cluster0.b6kryzo.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: DB_NAME
        value: moveere_prod
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: BCRYPT_ROUNDS
        value: 12
      - key: LOG_LEVEL
        value: info
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 50
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.vercel.app
      - key: OMDB_API_KEY
        value: b584f224
    healthCheckPath: /api/health
# No databases section needed - using MongoDB Atlas cloud service
